### ISSUE TITLE
Path query

### ISSUE THREAD

**Issue by ludions** [redFrik/yetanotheroscmovieplayer#2]
Hello Fredik, 

great to see this resurrected with additional functionality. Query re paths: works fine using full path as per Daniel's code, but  your default examples in SC and Max return a 'file not found' error from the yetanotheroscmovieplayer_osx. Should it look in 'data' dir as implied in your examples or is full path requirement correct behaviour? 

Best Wishes

Tom

**Comment by redFrik** [comment]
hi Tom!
(fond memories of developing this application together back in the days)
i belive it works like this: if only filename given then the app expects to find the file in the 'data' directory.  if a full path is given then go after that.
default examples work here but it could very well be that i messed something up.

**Comment by redFrik** [comment]
i found the problem! you were right... there was an issue with paths after all. but it only occurred after first getting a file-not-found and then any subsequent paths would not work properly.
many thanks for noticing. fixed in 87eebc33e1898a3f20f6403ca6fee90186911b99

**Comment by ludions** [comment]
Hello Fredrik, thanks but  I'm still seeing same problem. Whether I start with full path version (works), or 'no path' version ('n.sendMsg(\start, "yetanotherdemo.mov")), the latter never works in either context ('file yetanotherdemo.mov" not found!'). 
Happy to continue to test if you think it worth pursuing (would be nice to sort out if possible, but can obviously work around).

**Comment by redFrik** [comment]
strange indeed.  did you move the application somewhere?  are you running it from your Downloads folder?
for the 'no path' variant to work there needs to be a folder called 'data' next to / in the same folder as the .app

**Comment by ludions** [comment]
Yes, odd, as if using relative parth to 'data', the app shouldn't care too much where it is, though you're right to suspect permissions problem? IAC just running / not running your demo files. File location / dir structure  as follows:

Users/myhomedir/Projects/2021-yetanotheroscmovieplayer/2021-05-14-yetanotheroscmovieplayer-master/yetanotheroscmovieplayer\_osx.app 

/Users/myhomedir/Projects/2021-yetanotheroscmovieplayer/2021-05-14-yetanotheroscmovieplayer-master/data/yetanotherdemo.mov

**Comment by redFrik** [comment]
thanks.  i can recreate the problem here.
and a fix is to (believe it or not) take the .app and move it somewhere outside of the folder, and then move it back.

**Comment by ludions** [comment]
excellent! - works here also.

**Comment by redFrik** [comment]
great!  again thanks for finding this issue.
maybe some day i'll learn how to properly package and distribute apps.  but not today.
